# Generated by Django 3.1.4 on 2020-12-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('need_for_crawl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(auto_created=True)),
                ('text', models.TextField()),
                ('publish_date', models.DateField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.website')),
            ],
        ),
    ]
